import "Windows.Media.idl";

#include <sdkddkver.h>

namespace BufferTransform
{
	[version(NTDDI_WIN8)]
	runtimeclass BufferTransform
        {
            interface Windows.Media.IMediaExtension;
	}
}