import "Windows.Media.idl";

#include <sdkddkver.h>

namespace ObjectFinderEffectTransform
{
	[version(NTDDI_WIN8)]
	runtimeclass ObjectFinderEffectEffect
        {
            interface Windows.Media.IMediaExtension;
	}
}